-- SpazaSure Database Schema Migration
-- Generated from EF Core InitialCreate migration
-- Tables use snake_case naming (UseSnakeCaseNamingConvention)

BEGIN;
SELECT pg_advisory_xact_lock(hashtext('spazasure_schema_migration'));

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" varchar(150) NOT NULL,
    "ProductVersion" varchar(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE IF NOT EXISTS auth_audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id uuid,
    event text NOT NULL,
    ip_address text,
    user_agent text,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_AuthAuditLogs" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS categories (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    name text NOT NULL,
    slug text NOT NULL,
    parent_id uuid,
    icon_url text,
    sort_order smallint NOT NULL DEFAULT 0,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_Categories" PRIMARY KEY (id),
    CONSTRAINT "FK_Categories_Categories_ParentId" FOREIGN KEY (parent_id) REFERENCES categories(id)
);

CREATE TABLE IF NOT EXISTS permissions (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    name text NOT NULL,
    description text,
    module text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_Permissions" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS roles (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    name text NOT NULL,
    description text,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_Roles" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS role_permissions (
    role_id uuid NOT NULL,
    permission_id uuid NOT NULL,
    CONSTRAINT "PK_RolePermissions" PRIMARY KEY (role_id, permission_id),
    CONSTRAINT "FK_RolePermissions_Permissions_PermissionId" FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE,
    CONSTRAINT "FK_RolePermissions_Roles_RoleId" FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    phone text,
    email text,
    password_hash text,
    role_id uuid NOT NULL,
    status text NOT NULL DEFAULT 'active',
    mfa_enabled boolean NOT NULL DEFAULT false,
    mfa_secret text,
    failed_attempts smallint NOT NULL DEFAULT 0,
    locked_until timestamp with time zone,
    last_login_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_Users" PRIMARY KEY (id),
    CONSTRAINT "FK_Users_Roles_RoleId" FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS otp_codes (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid,
    phone text,
    email text,
    code text NOT NULL,
    purpose text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_OtpCodes" PRIMARY KEY (id),
    CONSTRAINT "FK_OtpCodes_Users_UserId" FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    token_hash text NOT NULL,
    device_info text,
    ip_address text,
    expires_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_RefreshTokens" PRIMARY KEY (id),
    CONSTRAINT "FK_RefreshTokens_Users_UserId" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Repair auth-critical columns when an earlier EnsureCreated race left partial tables.
ALTER TABLE auth_audit_logs ADD COLUMN IF NOT EXISTS user_id uuid;
ALTER TABLE auth_audit_logs ADD COLUMN IF NOT EXISTS event text;
ALTER TABLE auth_audit_logs ADD COLUMN IF NOT EXISTS ip_address text;
ALTER TABLE auth_audit_logs ADD COLUMN IF NOT EXISTS user_agent text;
ALTER TABLE auth_audit_logs ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT NOW();
ALTER TABLE roles ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE roles ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE roles ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;
ALTER TABLE roles ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT NOW();
ALTER TABLE roles ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT NOW();
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone text;
ALTER TABLE users ADD COLUMN IF NOT EXISTS email text;
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_hash text;
ALTER TABLE users ADD COLUMN IF NOT EXISTS role_id uuid;
ALTER TABLE users ADD COLUMN IF NOT EXISTS status text DEFAULT 'pending';
ALTER TABLE users ADD COLUMN IF NOT EXISTS mfa_enabled boolean DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS mfa_secret text;
ALTER TABLE users ADD COLUMN IF NOT EXISTS failed_attempts smallint DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS locked_until timestamp with time zone;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login_at timestamp with time zone;
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT NOW();
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT NOW();
ALTER TABLE refresh_tokens ADD COLUMN IF NOT EXISTS user_id uuid;
ALTER TABLE refresh_tokens ADD COLUMN IF NOT EXISTS token_hash text;
ALTER TABLE refresh_tokens ADD COLUMN IF NOT EXISTS device_info text;
ALTER TABLE refresh_tokens ADD COLUMN IF NOT EXISTS ip_address text;
ALTER TABLE refresh_tokens ADD COLUMN IF NOT EXISTS expires_at timestamp with time zone;
ALTER TABLE refresh_tokens ADD COLUMN IF NOT EXISTS revoked_at timestamp with time zone;
ALTER TABLE refresh_tokens ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT NOW();
ALTER TABLE refresh_tokens ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT NOW();

CREATE TABLE IF NOT EXISTS spaza_shops (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    shop_name text NOT NULL,
    owner_name text NOT NULL,
    owner_id_number text,
    phone text NOT NULL,
    email text,
    address text NOT NULL,
    city text,
    province text,
    postal_code text,
    latitude double precision,
    longitude double precision,
    status text NOT NULL DEFAULT 'pending',
    compliance_status text NOT NULL DEFAULT 'non_compliant',
    onboarding_fee_paid boolean NOT NULL DEFAULT false,
    onboarding_fee_ref text,
    rating_avg numeric(3,2) NOT NULL DEFAULT 0,
    rating_count integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_SpazaShops" PRIMARY KEY (id),
    CONSTRAINT "FK_SpazaShops_Users_UserId" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS shop_wallet_transactions (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    shop_id uuid NOT NULL,
    amount numeric(18,2) NOT NULL,
    type text NOT NULL DEFAULT 'top_up',
    status text NOT NULL DEFAULT 'pending',
    method text NOT NULL DEFAULT 'eft',
    reference text,
    notes text,
    approved_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_ShopWalletTransactions" PRIMARY KEY (id),
    CONSTRAINT "FK_ShopWalletTransactions_SpazaShops" FOREIGN KEY (shop_id) REFERENCES spaza_shops(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "IX_ShopWalletTransactions_ShopId" ON shop_wallet_transactions(shop_id);

CREATE TABLE IF NOT EXISTS shop_reviews (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    shop_id uuid NOT NULL,
    reviewer_user_id uuid NOT NULL,
    rating integer NOT NULL,
    comment text,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_ShopReviews" PRIMARY KEY (id),
    CONSTRAINT "FK_ShopReviews_SpazaShops" FOREIGN KEY (shop_id) REFERENCES spaza_shops(id) ON DELETE CASCADE,
    CONSTRAINT "FK_ShopReviews_Users" FOREIGN KEY (reviewer_user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT "UX_ShopReviews_ShopReviewer" UNIQUE (shop_id, reviewer_user_id)
);
CREATE INDEX IF NOT EXISTS "IX_ShopReviews_ShopId" ON shop_reviews(shop_id);

CREATE TABLE IF NOT EXISTS suppliers (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    company_name text NOT NULL,
    registration_number text,
    vat_number text,
    contact_person text NOT NULL,
    phone text NOT NULL,
    email text NOT NULL,
    address text,
    city text,
    province text,
    postal_code text,
    latitude double precision,
    longitude double precision,
    tier text NOT NULL DEFAULT 'bronze',
    status text NOT NULL DEFAULT 'pending',
    commission_rate numeric(4,2) NOT NULL DEFAULT 5.00,
    bank_name text,
    bank_account text,
    bank_branch_code text,
    logo_url text,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_Suppliers" PRIMARY KEY (id),
    CONSTRAINT "FK_Suppliers_Users_UserId" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS shop_documents (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    shop_id uuid NOT NULL,
    doc_type text NOT NULL,
    doc_url text,
    status text NOT NULL DEFAULT 'pending',
    verified_by uuid,
    verified_at timestamp with time zone,
    expiry_date date,
    rejection_note text,
    guidance_url text,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_ShopDocuments" PRIMARY KEY (id),
    CONSTRAINT "FK_ShopDocuments_SpazaShops_ShopId" FOREIGN KEY (shop_id) REFERENCES spaza_shops(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS supplier_documents (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    supplier_id uuid NOT NULL,
    doc_type text NOT NULL,
    doc_url text NOT NULL,
    status text NOT NULL DEFAULT 'pending',
    verified_by uuid,
    verified_at timestamp with time zone,
    expiry_date date,
    rejection_note text,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_SupplierDocuments" PRIMARY KEY (id),
    CONSTRAINT "FK_SupplierDocuments_Suppliers_SupplierId" FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS products (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    supplier_id uuid NOT NULL,
    category_id uuid,
    name text NOT NULL,
    description text,
    sku text NOT NULL,
    barcode text,
    price numeric(10,2) NOT NULL,
    min_order_qty integer NOT NULL DEFAULT 1,
    stock_qty integer NOT NULL DEFAULT 0,
    unit text NOT NULL DEFAULT 'unit',
    images text NOT NULL DEFAULT '[]',
    is_available boolean NOT NULL DEFAULT true,
    is_approved boolean NOT NULL DEFAULT false,
    approved_by uuid,
    approved_at timestamp with time zone,
    is_food_item boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_Products" PRIMARY KEY (id),
    CONSTRAINT "FK_Products_Categories_CategoryId" FOREIGN KEY (category_id) REFERENCES categories(id),
    CONSTRAINT "FK_Products_Suppliers_SupplierId" FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS orders (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    order_number text NOT NULL,
    shop_id uuid NOT NULL,
    supplier_id uuid NOT NULL,
    group_buy_id uuid,
    group_buy_participant_id uuid,
    status text NOT NULL DEFAULT 'pending',
    delivery_type text NOT NULL DEFAULT 'standard',
    delivery_address text,
    delivery_latitude double precision,
    delivery_longitude double precision,
    subtotal numeric(10,2) NOT NULL DEFAULT 0,
    delivery_fee numeric(10,2) NOT NULL DEFAULT 0,
    delivery_markup numeric(10,2) NOT NULL DEFAULT 50,
    delivery_distance_km numeric(10,2),
    platform_commission numeric(10,2) NOT NULL DEFAULT 0,
    total_amount numeric(10,2) NOT NULL DEFAULT 0,
    payment_method text NOT NULL DEFAULT 'invoice',
    payment_status text NOT NULL DEFAULT 'pending',
    rejection_reason text,
    notes text,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_Orders" PRIMARY KEY (id),
    CONSTRAINT "FK_Orders_SpazaShops_ShopId" FOREIGN KEY (shop_id) REFERENCES spaza_shops(id) ON DELETE CASCADE,
    CONSTRAINT "FK_Orders_Suppliers_SupplierId" FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS order_items (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    order_id uuid NOT NULL,
    product_id uuid NOT NULL,
    quantity integer NOT NULL,
    original_unit_price numeric(10,2) NOT NULL,
    unit_price numeric(10,2) NOT NULL,
    discount_pct numeric(5,2) NOT NULL DEFAULT 0,
    line_total numeric(10,2) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_OrderItems" PRIMARY KEY (id),
    CONSTRAINT "FK_OrderItems_Orders_OrderId" FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT "FK_OrderItems_Products_ProductId" FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS product_qr_codes (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    product_id uuid NOT NULL,
    order_item_id uuid,
    qr_code text NOT NULL,
    batch_number text,
    expiry_date date,
    is_scanned boolean NOT NULL DEFAULT false,
    scanned_at timestamp with time zone,
    is_recalled boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_ProductQrCodes" PRIMARY KEY (id),
    CONSTRAINT "FK_ProductQrCodes_Products_ProductId" FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

-- Allergen tags per product, for the Customer role's allergen-warning
-- feature. Stored as a JSON-array string (e.g. ["peanuts","dairy"]),
-- matching the same convention as products.images above, rather than a
-- jsonb column — keeps the C# side a plain string property with no
-- Npgsql column-type mismatch risk.
ALTER TABLE products ADD COLUMN IF NOT EXISTS allergens text NOT NULL DEFAULT '[]';

-- ── Customer role ────────────────────────────────────────────────────────
-- Lightweight profile — customers don't run a business, so this is just
-- personal details + declared allergies, unlike suppliers/spaza_shops.
CREATE TABLE IF NOT EXISTS customer_profiles (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    first_name text NOT NULL,
    last_name text NOT NULL,
    age integer,
    allergies text NOT NULL DEFAULT '[]',
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_CustomerProfiles" PRIMARY KEY (id),
    CONSTRAINT "FK_CustomerProfiles_Users_UserId" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT "UQ_CustomerProfiles_UserId" UNIQUE (user_id)
);

-- Upgrade databases created before customer names were split. Keep the old
-- full_name column intact for backwards compatibility with existing data.
ALTER TABLE customer_profiles ADD COLUMN IF NOT EXISTS first_name text;
ALTER TABLE customer_profiles ADD COLUMN IF NOT EXISTS last_name text;
ALTER TABLE customer_profiles ADD COLUMN IF NOT EXISTS age integer;
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'customer_profiles' AND column_name = 'full_name'
    ) THEN
        EXECUTE $sql$
            UPDATE customer_profiles
            SET
                first_name = COALESCE(NULLIF(first_name, ''), split_part(full_name, ' ', 1), ''),
                last_name = COALESCE(NULLIF(last_name, ''), NULLIF(trim(substr(full_name, length(split_part(full_name, ' ', 1)) + 1)), ''), '')
            WHERE first_name IS NULL OR last_name IS NULL
        $sql$;
    END IF;
END $$;
ALTER TABLE customer_profiles ALTER COLUMN first_name SET DEFAULT '';
ALTER TABLE customer_profiles ALTER COLUMN last_name SET DEFAULT '';
UPDATE customer_profiles SET first_name = '' WHERE first_name IS NULL;
UPDATE customer_profiles SET last_name = '' WHERE last_name IS NULL;
ALTER TABLE customer_profiles ALTER COLUMN first_name SET NOT NULL;
ALTER TABLE customer_profiles ALTER COLUMN last_name SET NOT NULL;

CREATE TABLE IF NOT EXISTS customer_scan_events (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    customer_user_id uuid NOT NULL,
    code text NOT NULL,
    product_id uuid,
    source text NOT NULL DEFAULT 'unknown',
    points_awarded integer NOT NULL DEFAULT 5,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_CustomerScanEvents" PRIMARY KEY (id),
    CONSTRAINT "FK_CustomerScanEvents_Users" FOREIGN KEY (customer_user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT "FK_CustomerScanEvents_Products" FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS "IX_CustomerScanEvents_CustomerCodeDate" ON customer_scan_events(customer_user_id, code, created_at);

CREATE TABLE IF NOT EXISTS customer_reward_transactions (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    customer_user_id uuid NOT NULL,
    points integer NOT NULL,
    type text NOT NULL DEFAULT 'scan',
    reference text,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_CustomerRewardTransactions" PRIMARY KEY (id),
    CONSTRAINT "FK_CustomerRewardTransactions_Users" FOREIGN KEY (customer_user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "IX_CustomerRewardTransactions_CustomerDate" ON customer_reward_transactions(customer_user_id, created_at);

CREATE TABLE IF NOT EXISTS customer_vouchers (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    customer_user_id uuid NOT NULL,
    code text NOT NULL,
    amount numeric(10,2) NOT NULL DEFAULT 20,
    status text NOT NULL DEFAULT 'active',
    redeemed_at timestamp with time zone,
    redeemed_by_user_id uuid,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_CustomerVouchers" PRIMARY KEY (id),
    CONSTRAINT "FK_CustomerVouchers_Users" FOREIGN KEY (customer_user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT "UQ_CustomerVouchers_Code" UNIQUE (code)
);
CREATE INDEX IF NOT EXISTS "IX_CustomerVouchers_CustomerStatus" ON customer_vouchers(customer_user_id, status);

-- A scan a customer (or retailer) flagged as suspicious, escalatable by
-- admin to an external health authority. product_id is nullable because a
-- report can be filed against a barcode SpazaSure doesn't even recognize.
CREATE TABLE IF NOT EXISTS reports (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    reporter_user_id uuid NOT NULL,
    product_id uuid,
    barcode text,
    report_type text,
    shop_name text,
    is_anonymous boolean NOT NULL DEFAULT false,
    description text NOT NULL,
    photo_url text,
    batch_number text,
    expiry_date date,
    purchase_location text,
    supplier_name text,
    status text NOT NULL DEFAULT 'submitted',
    escalated_to text,
    escalated_at timestamp with time zone,
    resolution_note text,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_Reports" PRIMARY KEY (id),
    CONSTRAINT "FK_Reports_Users_ReporterUserId" FOREIGN KEY (reporter_user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT "FK_Reports_Products_ProductId" FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS "IX_Reports_ReporterUserId" ON reports(reporter_user_id);
CREATE INDEX IF NOT EXISTS "IX_Reports_Status" ON reports(status);

CREATE TABLE IF NOT EXISTS subscription_plans (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    tier text NOT NULL,
    name text NOT NULL,
    description text NOT NULL DEFAULT '',
    monthly_price numeric(10,2) NOT NULL DEFAULT 0,
    annual_price numeric(10,2) NOT NULL DEFAULT 0,
    commission_rate numeric(4,2) NOT NULL DEFAULT 5,
    max_listings integer NOT NULL DEFAULT 10,
    max_orders integer NOT NULL DEFAULT 50,
    has_analytics boolean NOT NULL DEFAULT false,
    has_priority_support boolean NOT NULL DEFAULT false,
    has_bulk_pricing boolean NOT NULL DEFAULT false,
    has_api_access boolean NOT NULL DEFAULT false,
    has_custom_branding boolean NOT NULL DEFAULT false,
    is_active boolean NOT NULL DEFAULT true,
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone DEFAULT NOW(),
    CONSTRAINT "PK_SubscriptionPlans" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS supplier_subscriptions (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    supplier_id uuid NOT NULL,
    plan_id uuid NOT NULL,
    billing_cycle text NOT NULL DEFAULT 'monthly',
    status text NOT NULL DEFAULT 'active',
    start_date timestamp with time zone NOT NULL DEFAULT NOW(),
    end_date timestamp with time zone,
    next_billing_date timestamp with time zone,
    amount_paid numeric(10,2) NOT NULL DEFAULT 0,
    payment_reference text,
    payment_method text,
    cancelled_reason text,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone DEFAULT NOW(),
    CONSTRAINT "PK_SupplierSubscriptions" PRIMARY KEY (id),
    CONSTRAINT "FK_SupplierSubscriptions_Suppliers_SupplierId" FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE,
    CONSTRAINT "FK_SupplierSubscriptions_SubscriptionPlans_PlanId" FOREIGN KEY (plan_id) REFERENCES subscription_plans(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS group_buys (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    title text NOT NULL,
    description text,
    product_id uuid NOT NULL,
    supplier_id uuid NOT NULL,
    target_qty integer NOT NULL,
    current_qty integer NOT NULL DEFAULT 0,
    original_price numeric(10,2) NOT NULL,
    discount_price numeric(10,2) NOT NULL,
    discount_pct integer NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    status text NOT NULL DEFAULT 'active',
    created_by_shop_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone DEFAULT NOW(),
    CONSTRAINT "PK_GroupBuys" PRIMARY KEY (id),
    CONSTRAINT "FK_GroupBuys_Products_ProductId" FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    CONSTRAINT "FK_GroupBuys_Suppliers_SupplierId" FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE,
    CONSTRAINT "FK_GroupBuys_SpazaShops_CreatedByShopId" FOREIGN KEY (created_by_shop_id) REFERENCES spaza_shops(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS group_buy_participants (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    group_buy_id uuid NOT NULL,
    shop_id uuid NOT NULL,
    quantity integer NOT NULL,
    status text NOT NULL DEFAULT 'joined',
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone DEFAULT NOW(),
    CONSTRAINT "PK_GroupBuyParticipants" PRIMARY KEY (id),
    CONSTRAINT "FK_GroupBuyParticipants_GroupBuys_GroupBuyId" FOREIGN KEY (group_buy_id) REFERENCES group_buys(id) ON DELETE CASCADE,
    CONSTRAINT "FK_GroupBuyParticipants_SpazaShops_ShopId" FOREIGN KEY (shop_id) REFERENCES spaza_shops(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS group_buy_products (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    group_buy_id uuid NOT NULL,
    product_id uuid NOT NULL,
    original_price numeric(10,2) NOT NULL,
    discount_price numeric(10,2) NOT NULL,
    discount_pct integer NOT NULL,
    target_qty integer NOT NULL,
    current_qty integer NOT NULL DEFAULT 0,
    status text NOT NULL DEFAULT 'active',
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone DEFAULT NOW(),
    CONSTRAINT "PK_GroupBuyProducts" PRIMARY KEY (id),
    CONSTRAINT "FK_GroupBuyProducts_GroupBuys_GroupBuyId" FOREIGN KEY (group_buy_id) REFERENCES group_buys(id) ON DELETE CASCADE,
    CONSTRAINT "FK_GroupBuyProducts_Products_ProductId" FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS group_buy_participant_items (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    participant_id uuid NOT NULL,
    group_buy_product_id uuid NOT NULL,
    quantity integer NOT NULL,
    status text NOT NULL DEFAULT 'joined',
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone DEFAULT NOW(),
    CONSTRAINT "PK_GroupBuyParticipantItems" PRIMARY KEY (id),
    CONSTRAINT "FK_GroupBuyParticipantItems_GroupBuyParticipants_ParticipantId" FOREIGN KEY (participant_id) REFERENCES group_buy_participants(id) ON DELETE CASCADE,
    CONSTRAINT "FK_GroupBuyParticipantItems_GroupBuyProducts_GroupBuyProductId" FOREIGN KEY (group_buy_product_id) REFERENCES group_buy_products(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS platform_settings (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    key text NOT NULL,
    value text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_PlatformSettings" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS shop_onboarding_payments (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    shop_id uuid NOT NULL,
    amount numeric(10,2) NOT NULL,
    status text NOT NULL DEFAULT 'pending',
    pay_fast_payment_id text,
    expires_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_ShopOnboardingPayments" PRIMARY KEY (id),
    CONSTRAINT "FK_ShopOnboardingPayments_SpazaShops_ShopId"
        FOREIGN KEY (shop_id) REFERENCES spaza_shops(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS notifications (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    supplier_id text NOT NULL,
    type varchar(50) NOT NULL,
    title varchar(255) NOT NULL,
    message varchar(1000) NOT NULL,
    priority varchar(20) NOT NULL DEFAULT 'normal',
    is_read boolean NOT NULL DEFAULT false,
    reference_id varchar(255),
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_Notifications" PRIMARY KEY (id)
);

-- Repair columns introduced after the baseline for existing databases. Fresh tables
-- above include the same definitions, so these statements are repeat-run safe.
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS latitude double precision;
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS longitude double precision;
ALTER TABLE spaza_shops ADD COLUMN IF NOT EXISTS latitude double precision;
ALTER TABLE spaza_shops ADD COLUMN IF NOT EXISTS longitude double precision;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS group_buy_participant_id uuid;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_latitude double precision;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_longitude double precision;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_distance_km numeric(10,2);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_method text NOT NULL DEFAULT 'invoice';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_status text NOT NULL DEFAULT 'pending';
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS original_unit_price numeric(10,2);
UPDATE order_items SET original_unit_price = unit_price WHERE original_unit_price IS NULL;
ALTER TABLE order_items ALTER COLUMN original_unit_price TYPE numeric(10,2)
    USING original_unit_price::numeric(10,2);
ALTER TABLE order_items ALTER COLUMN original_unit_price SET NOT NULL;
ALTER TABLE group_buy_products ADD COLUMN IF NOT EXISTS group_buy_id uuid;
ALTER TABLE group_buy_products ADD COLUMN IF NOT EXISTS product_id uuid;
ALTER TABLE group_buy_products ADD COLUMN IF NOT EXISTS original_price numeric(10,2);
ALTER TABLE group_buy_products ADD COLUMN IF NOT EXISTS discount_price numeric(10,2);
ALTER TABLE group_buy_products ADD COLUMN IF NOT EXISTS discount_pct integer;
ALTER TABLE group_buy_products ADD COLUMN IF NOT EXISTS target_qty integer;
ALTER TABLE group_buy_products ADD COLUMN IF NOT EXISTS current_qty integer DEFAULT 0;
ALTER TABLE group_buy_products ADD COLUMN IF NOT EXISTS status text DEFAULT 'active';
ALTER TABLE group_buy_products ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT NOW();
ALTER TABLE group_buy_products ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT NOW();
ALTER TABLE group_buy_participant_items ADD COLUMN IF NOT EXISTS participant_id uuid;
ALTER TABLE group_buy_participant_items ADD COLUMN IF NOT EXISTS group_buy_product_id uuid;
ALTER TABLE group_buy_participant_items ADD COLUMN IF NOT EXISTS quantity integer;
ALTER TABLE group_buy_participant_items ADD COLUMN IF NOT EXISTS status text DEFAULT 'joined';
ALTER TABLE group_buy_participant_items ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT NOW();
ALTER TABLE group_buy_participant_items ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT NOW();

-- Normalize pre-existing order column types while preserving nullable delivery distance.
ALTER TABLE orders ALTER COLUMN delivery_distance_km DROP DEFAULT;
ALTER TABLE orders ALTER COLUMN delivery_distance_km DROP NOT NULL;
ALTER TABLE orders ALTER COLUMN delivery_distance_km TYPE numeric(10,2)
    USING delivery_distance_km::numeric(10,2);
UPDATE orders SET payment_method = 'invoice' WHERE payment_method IS NULL;
UPDATE orders SET payment_status = 'pending' WHERE payment_status IS NULL;
ALTER TABLE orders ALTER COLUMN payment_method SET DEFAULT 'invoice';
ALTER TABLE orders ALTER COLUMN payment_method SET NOT NULL;
ALTER TABLE orders ALTER COLUMN payment_status SET DEFAULT 'pending';
ALTER TABLE orders ALTER COLUMN payment_status SET NOT NULL;

-- Temporarily remove known application/migration unique indexes so reference
-- consolidation cannot fail when two duplicate parents already have child rows.
DROP INDEX IF EXISTS "UX_GroupBuyProducts_GroupBuyId_ProductId";
DROP INDEX IF EXISTS "IX_GroupBuyProducts_GroupBuyId_ProductId";
DROP INDEX IF EXISTS "UX_GroupBuyParticipants_GroupBuyId_ShopId";
DROP INDEX IF EXISTS "IX_GroupBuyParticipants_GroupBuyId_ShopId";
DROP INDEX IF EXISTS "UX_GroupBuyParticipantItems_ParticipantId_GroupBuyProductId";
DROP INDEX IF EXISTS "IX_GroupBuyParticipantItems_ParticipantId_GroupBuyProductId";

-- Consolidate duplicate normalized products before enforcing uniqueness. Related
-- item quantities remain attached to the deterministic oldest product row.
WITH ranked AS (
    SELECT id,
           FIRST_VALUE(id) OVER (
               PARTITION BY group_buy_id, product_id
               ORDER BY created_at NULLS LAST, id
           ) AS keep_id,
           ROW_NUMBER() OVER (
               PARTITION BY group_buy_id, product_id
               ORDER BY created_at NULLS LAST, id
           ) AS rn
    FROM group_buy_products
)
UPDATE group_buy_participant_items item
SET group_buy_product_id = ranked.keep_id
FROM ranked
WHERE ranked.rn > 1
  AND item.group_buy_product_id = ranked.id;

WITH ranked AS (
    SELECT id,
           ROW_NUMBER() OVER (
               PARTITION BY group_buy_id, product_id
               ORDER BY created_at NULLS LAST, id
           ) AS rn
    FROM group_buy_products
)
DELETE FROM group_buy_products product
USING ranked
WHERE product.id = ranked.id
  AND ranked.rn > 1;

-- Consolidate duplicate participants by summing their legacy quantities and
-- retaining the strongest active status on the deterministic oldest row.
WITH participant_rollup AS (
    SELECT group_buy_id,
           shop_id,
           (ARRAY_AGG(id ORDER BY created_at NULLS LAST, id))[1] AS keep_id,
           SUM(quantity)::integer AS quantity,
           CASE
               WHEN BOOL_OR(status = 'confirmed') THEN 'confirmed'
               WHEN BOOL_OR(status = 'joined') THEN 'joined'
               ELSE 'cancelled'
           END AS status
    FROM group_buy_participants
    GROUP BY group_buy_id, shop_id
)
UPDATE group_buy_participants participant
SET quantity = rollup.quantity,
    status = rollup.status,
    updated_at = COALESCE(participant.updated_at, NOW())
FROM participant_rollup rollup
WHERE participant.id = rollup.keep_id;

WITH ranked AS (
    SELECT id,
           FIRST_VALUE(id) OVER (
               PARTITION BY group_buy_id, shop_id
               ORDER BY created_at NULLS LAST, id
           ) AS keep_id,
           ROW_NUMBER() OVER (
               PARTITION BY group_buy_id, shop_id
               ORDER BY created_at NULLS LAST, id
           ) AS rn
    FROM group_buy_participants
)
UPDATE group_buy_participant_items item
SET participant_id = ranked.keep_id
FROM ranked
WHERE ranked.rn > 1
  AND item.participant_id = ranked.id;

WITH ranked AS (
    SELECT id,
           ROW_NUMBER() OVER (
               PARTITION BY group_buy_id, shop_id
               ORDER BY created_at NULLS LAST, id
           ) AS rn
    FROM group_buy_participants
)
DELETE FROM group_buy_participants participant
USING ranked
WHERE participant.id = ranked.id
  AND ranked.rn > 1;

-- Any duplicate participant/product item rows created by consolidation are
-- merged by quantity rather than discarded.
WITH item_rollup AS (
    SELECT participant_id,
           group_buy_product_id,
           (ARRAY_AGG(id ORDER BY created_at NULLS LAST, id))[1] AS keep_id,
           SUM(quantity)::integer AS quantity,
           CASE
               WHEN BOOL_OR(status = 'confirmed') THEN 'confirmed'
               WHEN BOOL_OR(status = 'joined') THEN 'joined'
               ELSE 'cancelled'
           END AS status
    FROM group_buy_participant_items
    GROUP BY participant_id, group_buy_product_id
)
UPDATE group_buy_participant_items item
SET quantity = rollup.quantity,
    status = rollup.status,
    updated_at = COALESCE(item.updated_at, NOW())
FROM item_rollup rollup
WHERE item.id = rollup.keep_id;

WITH ranked AS (
    SELECT id,
           ROW_NUMBER() OVER (
               PARTITION BY participant_id, group_buy_product_id
               ORDER BY created_at NULLS LAST, id
           ) AS rn
    FROM group_buy_participant_items
)
DELETE FROM group_buy_participant_items item
USING ranked
WHERE item.id = ranked.id
  AND ranked.rn > 1;

-- Remove malformed partial normalized rows before deterministic backfill. These
-- rows cannot represent usable business data; legacy scalar rows remain intact.
DELETE FROM group_buy_participant_items item
WHERE item.participant_id IS NULL
   OR item.group_buy_product_id IS NULL
   OR item.quantity IS NULL
   OR item.status IS NULL
   OR NOT EXISTS (SELECT 1 FROM group_buy_participants participant WHERE participant.id = item.participant_id)
   OR NOT EXISTS (SELECT 1 FROM group_buy_products product WHERE product.id = item.group_buy_product_id);

DELETE FROM group_buy_products normalized
WHERE normalized.group_buy_id IS NULL
   OR normalized.product_id IS NULL
   OR normalized.original_price IS NULL
   OR normalized.discount_price IS NULL
   OR normalized.discount_pct IS NULL
   OR normalized.target_qty IS NULL
   OR normalized.current_qty IS NULL
   OR normalized.status IS NULL
   OR NOT EXISTS (SELECT 1 FROM group_buys group_buy WHERE group_buy.id = normalized.group_buy_id)
   OR NOT EXISTS (SELECT 1 FROM products product WHERE product.id = normalized.product_id);

-- Legacy `completed` meant the target was reached, before supplier approval
-- was a separate finalization step. Reopen only unnormalized campaigns with no
-- generated orders so they can be approved under the normalized workflow.
UPDATE group_buys group_buy
SET status = 'active',
    updated_at = NOW()
WHERE group_buy.status = 'completed'
  AND NOT EXISTS (SELECT 1 FROM orders order_row WHERE order_row.group_buy_id = group_buy.id);

-- Backfill exactly one normalized product for each legacy scalar group. The
-- group id is reused when available, making fresh backfills deterministic.
INSERT INTO group_buy_products (
    id, group_buy_id, product_id, original_price, discount_price, discount_pct,
    target_qty, current_qty, status, created_at, updated_at
)
SELECT CASE
           WHEN EXISTS (SELECT 1 FROM group_buy_products by_id WHERE by_id.id = group_buy.id)
               THEN gen_random_uuid()
           ELSE group_buy.id
       END,
       group_buy.id,
       group_buy.product_id,
       group_buy.original_price,
       group_buy.discount_price,
       group_buy.discount_pct,
       group_buy.target_qty,
       group_buy.current_qty,
       CASE
           WHEN EXISTS (SELECT 1 FROM orders order_row WHERE order_row.group_buy_id = group_buy.id)
               THEN 'completed'
           WHEN group_buy.status IN ('cancelled', 'expired') THEN group_buy.status
           WHEN group_buy.current_qty >= group_buy.target_qty THEN 'qualified'
           ELSE 'active'
       END,
       group_buy.created_at,
       group_buy.updated_at
FROM group_buys group_buy
WHERE NOT EXISTS (
    SELECT 1
    FROM group_buy_products normalized
    WHERE normalized.group_buy_id = group_buy.id
      AND normalized.product_id = group_buy.product_id
);

-- Backfill one normalized item per retained legacy participant, preserving its
-- quantity and status and linking it to the legacy group's normalized product.
INSERT INTO group_buy_participant_items (
    id, participant_id, group_buy_product_id, quantity, status, created_at, updated_at
)
SELECT CASE
           WHEN EXISTS (SELECT 1 FROM group_buy_participant_items by_id WHERE by_id.id = participant.id)
               THEN gen_random_uuid()
           ELSE participant.id
       END,
       participant.id,
       normalized.id,
       participant.quantity,
       participant.status,
       participant.created_at,
       participant.updated_at
FROM group_buy_participants participant
JOIN group_buys group_buy ON group_buy.id = participant.group_buy_id
JOIN LATERAL (
    SELECT product.id
    FROM group_buy_products product
    WHERE product.group_buy_id = group_buy.id
      AND product.product_id = group_buy.product_id
    ORDER BY product.created_at NULLS LAST, product.id
    LIMIT 1
) normalized ON true
WHERE NOT EXISTS (
    SELECT 1
    FROM group_buy_participant_items item
    WHERE item.participant_id = participant.id
      AND item.group_buy_product_id = normalized.id
);

-- Tighten repaired normalized columns after malformed partial rows are removed
-- and deterministic backfills are complete.
UPDATE group_buy_products SET current_qty = 0 WHERE current_qty IS NULL;
UPDATE group_buy_products SET status = 'active' WHERE status IS NULL;
UPDATE group_buy_products SET created_at = NOW() WHERE created_at IS NULL;
UPDATE group_buy_participant_items SET status = 'joined' WHERE status IS NULL;
UPDATE group_buy_participant_items SET created_at = NOW() WHERE created_at IS NULL;
ALTER TABLE group_buy_products ALTER COLUMN group_buy_id SET NOT NULL;
ALTER TABLE group_buy_products ALTER COLUMN product_id SET NOT NULL;
ALTER TABLE group_buy_products ALTER COLUMN original_price SET NOT NULL;
ALTER TABLE group_buy_products ALTER COLUMN discount_price SET NOT NULL;
ALTER TABLE group_buy_products ALTER COLUMN discount_pct SET NOT NULL;
ALTER TABLE group_buy_products ALTER COLUMN target_qty SET NOT NULL;
ALTER TABLE group_buy_products ALTER COLUMN current_qty SET DEFAULT 0;
ALTER TABLE group_buy_products ALTER COLUMN current_qty SET NOT NULL;
ALTER TABLE group_buy_products ALTER COLUMN status SET DEFAULT 'active';
ALTER TABLE group_buy_products ALTER COLUMN status SET NOT NULL;
ALTER TABLE group_buy_products ALTER COLUMN created_at SET DEFAULT NOW();
ALTER TABLE group_buy_products ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE group_buy_participant_items ALTER COLUMN participant_id SET NOT NULL;
ALTER TABLE group_buy_participant_items ALTER COLUMN group_buy_product_id SET NOT NULL;
ALTER TABLE group_buy_participant_items ALTER COLUMN quantity SET NOT NULL;
ALTER TABLE group_buy_participant_items ALTER COLUMN status SET DEFAULT 'joined';
ALTER TABLE group_buy_participant_items ALTER COLUMN status SET NOT NULL;
ALTER TABLE group_buy_participant_items ALTER COLUMN created_at SET DEFAULT NOW();
ALTER TABLE group_buy_participant_items ALTER COLUMN created_at SET NOT NULL;

-- Shop-created pricing is pending until supplier approval. Reset every
-- unapproved normalized product, including products still pending after a
-- partial approval. Approved/completed product prices and existing order lines
-- are left untouched.
UPDATE group_buy_products product
SET discount_price = product.original_price,
    discount_pct = 0,
    updated_at = NOW()
WHERE product.status IN ('active', 'qualified');

-- Keep the legacy scalar mirror aligned only when its deterministic first
-- normalized product is itself still awaiting supplier pricing.
WITH first_products AS (
    SELECT DISTINCT ON (product.group_buy_id)
           product.group_buy_id,
           product.product_id,
           product.target_qty,
           product.current_qty,
           product.original_price,
           product.discount_price,
           product.discount_pct,
           product.status
    FROM group_buy_products product
    JOIN group_buys group_buy ON group_buy.id = product.group_buy_id
    ORDER BY product.group_buy_id,
             (product.product_id = group_buy.product_id) DESC,
             product.created_at NULLS LAST,
             product.id
)
UPDATE group_buys group_buy
SET product_id = first_product.product_id,
    target_qty = first_product.target_qty,
    current_qty = first_product.current_qty,
    original_price = first_product.original_price,
    discount_price = first_product.discount_price,
    discount_pct = first_product.discount_pct,
    updated_at = NOW()
FROM first_products first_product
WHERE group_buy.id = first_product.group_buy_id
  AND first_product.status IN ('active', 'qualified');

-- A shop may have only one order association per group buy. Keep every order,
-- but retain the oldest association and clear later duplicate associations.
WITH ranked AS (
    SELECT id,
           ROW_NUMBER() OVER (
               PARTITION BY group_buy_id, shop_id
               ORDER BY created_at NULLS LAST, id
           ) AS rn
    FROM orders
    WHERE group_buy_id IS NOT NULL
)
UPDATE orders order_row
SET group_buy_id = NULL,
    updated_at = COALESCE(order_row.updated_at, NOW())
FROM ranked
WHERE order_row.id = ranked.id
  AND ranked.rn > 1;

-- Invalid legacy group associations cannot satisfy the delayed FK; preserve the
-- orders themselves while clearing only the orphaned optional association.
UPDATE orders order_row
SET group_buy_id = NULL,
    updated_at = COALESCE(order_row.updated_at, NOW())
WHERE order_row.group_buy_id IS NOT NULL
  AND NOT EXISTS (
      SELECT 1 FROM group_buys group_buy WHERE group_buy.id = order_row.group_buy_id
  );

-- A participant may be linked to only one order. Preserve every order, but clear
-- later duplicate optional links so the participant unique index is repeat-run safe.
WITH ranked AS (
    SELECT id,
           ROW_NUMBER() OVER (
               PARTITION BY group_buy_participant_id
               ORDER BY created_at NULLS LAST, id
           ) AS rn
    FROM orders
    WHERE group_buy_participant_id IS NOT NULL
)
UPDATE orders order_row
SET group_buy_participant_id = NULL,
    updated_at = COALESCE(order_row.updated_at, NOW())
FROM ranked
WHERE order_row.id = ranked.id
  AND ranked.rn > 1;

UPDATE orders order_row
SET group_buy_participant_id = NULL,
    updated_at = COALESCE(order_row.updated_at, NOW())
WHERE order_row.group_buy_participant_id IS NOT NULL
  AND NOT EXISTS (
      SELECT 1 FROM group_buy_participants participant
      WHERE participant.id = order_row.group_buy_participant_id
  );

-- Recreate delete behaviors that must match the EF model. Named constraints make
-- these operations deterministic and safe on every script run.
ALTER TABLE group_buy_products
    DROP CONSTRAINT IF EXISTS "FK_GroupBuyProducts_Products_ProductId";
ALTER TABLE group_buy_participant_items
    DROP CONSTRAINT IF EXISTS "FK_GroupBuyParticipantItems_GroupBuyProducts_GroupBuyProductId";

-- Orders are created before group_buys in this baseline, so add that FK later.
-- Existing normalized constraints are created or validated once repaired rows
-- and deterministic backfills satisfy the complete model.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'orders'::regclass
          AND conname = 'FK_Orders_GroupBuys_GroupBuyId'
    ) THEN
        ALTER TABLE orders
            ADD CONSTRAINT "FK_Orders_GroupBuys_GroupBuyId"
            FOREIGN KEY (group_buy_id) REFERENCES group_buys(id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'orders'::regclass
          AND conname = 'FK_Orders_GroupBuyParticipants_GroupBuyParticipantId'
    ) THEN
        ALTER TABLE orders
            ADD CONSTRAINT "FK_Orders_GroupBuyParticipants_GroupBuyParticipantId"
            FOREIGN KEY (group_buy_participant_id) REFERENCES group_buy_participants(id) ON DELETE RESTRICT;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'group_buy_products'::regclass
          AND conname = 'FK_GroupBuyProducts_GroupBuys_GroupBuyId'
    ) THEN
        ALTER TABLE group_buy_products
            ADD CONSTRAINT "FK_GroupBuyProducts_GroupBuys_GroupBuyId"
            FOREIGN KEY (group_buy_id) REFERENCES group_buys(id) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'group_buy_products'::regclass
          AND conname = 'FK_GroupBuyProducts_Products_ProductId'
    ) THEN
        ALTER TABLE group_buy_products
            ADD CONSTRAINT "FK_GroupBuyProducts_Products_ProductId"
            FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'group_buy_participant_items'::regclass
          AND conname = 'FK_GroupBuyParticipantItems_GroupBuyParticipants_ParticipantId'
    ) THEN
        ALTER TABLE group_buy_participant_items
            ADD CONSTRAINT "FK_GroupBuyParticipantItems_GroupBuyParticipants_ParticipantId"
            FOREIGN KEY (participant_id) REFERENCES group_buy_participants(id) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'group_buy_participant_items'::regclass
          AND conname = 'FK_GroupBuyParticipantItems_GroupBuyProducts_GroupBuyProductId'
    ) THEN
        ALTER TABLE group_buy_participant_items
            ADD CONSTRAINT "FK_GroupBuyParticipantItems_GroupBuyProducts_GroupBuyProductId"
            FOREIGN KEY (group_buy_product_id) REFERENCES group_buy_products(id) ON DELETE RESTRICT;
    END IF;
END $$;

-- Indexes
CREATE INDEX IF NOT EXISTS "IX_Categories_ParentId" ON categories(parent_id);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Permissions_Name" ON permissions(name);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Roles_Name" ON roles(name);
CREATE INDEX IF NOT EXISTS "IX_Users_RoleId" ON users(role_id);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_Email" ON users(email);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_Phone" ON users(phone);
CREATE INDEX IF NOT EXISTS "IX_OtpCodes_UserId" ON otp_codes(user_id);
CREATE INDEX IF NOT EXISTS "IX_RefreshTokens_UserId" ON refresh_tokens(user_id);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_SpazaShops_UserId" ON spaza_shops(user_id);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Suppliers_UserId" ON suppliers(user_id);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Suppliers_RegistrationNumber" ON suppliers(registration_number);
CREATE INDEX IF NOT EXISTS "IX_ShopDocuments_ShopId" ON shop_documents(shop_id);
CREATE INDEX IF NOT EXISTS "IX_SupplierDocuments_SupplierId" ON supplier_documents(supplier_id);
CREATE INDEX IF NOT EXISTS "IX_Products_CategoryId" ON products(category_id);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Products_SupplierId_Sku" ON products(supplier_id, sku);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Orders_OrderNumber" ON orders(order_number);
CREATE INDEX IF NOT EXISTS "IX_Orders_ShopId" ON orders(shop_id);
CREATE INDEX IF NOT EXISTS "IX_Orders_SupplierId" ON orders(supplier_id);
CREATE INDEX IF NOT EXISTS "IX_Orders_GroupBuyId" ON orders(group_buy_id);
CREATE UNIQUE INDEX IF NOT EXISTS "UX_Orders_GroupBuyParticipantId"
    ON orders(group_buy_participant_id) WHERE group_buy_participant_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "UX_Orders_GroupBuyId_ShopId"
    ON orders(group_buy_id, shop_id) WHERE group_buy_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS "IX_OrderItems_OrderId" ON order_items(order_id);
CREATE INDEX IF NOT EXISTS "IX_OrderItems_ProductId" ON order_items(product_id);
CREATE INDEX IF NOT EXISTS "IX_ProductQrCodes_ProductId" ON product_qr_codes(product_id);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_ProductQrCodes_QrCode" ON product_qr_codes(qr_code);

-- Keep exactly one stable, product-level QR token while still allowing future
-- order-item QR codes. Remove duplicate legacy defaults before enforcing it.
WITH ranked AS (
    SELECT id, ROW_NUMBER() OVER (
        PARTITION BY product_id ORDER BY created_at NULLS LAST, id
    ) AS rn
    FROM product_qr_codes
    WHERE order_item_id IS NULL
)
DELETE FROM product_qr_codes qr
USING ranked
WHERE qr.id = ranked.id AND ranked.rn > 1;

CREATE UNIQUE INDEX IF NOT EXISTS "UX_ProductQrCodes_DefaultProduct"
    ON product_qr_codes(product_id) WHERE order_item_id IS NULL;

-- Backfill opaque, persisted QR tokens for legacy products. Existing tokens are
-- never replaced, so printed labels remain valid across repeated migrations.
INSERT INTO product_qr_codes (
    id, product_id, qr_code, is_scanned, is_recalled, created_at, updated_at
)
SELECT gen_random_uuid(), product.id,
       'SPZQR-' || UPPER(ENCODE(gen_random_bytes(16), 'hex')),
       false, false, NOW(), NOW()
FROM products product
WHERE NOT EXISTS (
    SELECT 1 FROM product_qr_codes qr
    WHERE qr.product_id = product.id AND qr.order_item_id IS NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_SubscriptionPlans_Tier" ON subscription_plans(tier);
CREATE INDEX IF NOT EXISTS "IX_SupplierSubscriptions_SupplierId" ON supplier_subscriptions(supplier_id);
CREATE INDEX IF NOT EXISTS "IX_SupplierSubscriptions_PlanId" ON supplier_subscriptions(plan_id);
CREATE INDEX IF NOT EXISTS "IX_GroupBuys_ProductId" ON group_buys(product_id);
CREATE INDEX IF NOT EXISTS "IX_GroupBuys_SupplierId" ON group_buys(supplier_id);
CREATE INDEX IF NOT EXISTS "IX_GroupBuys_CreatedByShopId" ON group_buys(created_by_shop_id);
CREATE INDEX IF NOT EXISTS "IX_GroupBuys_Status" ON group_buys(status);
CREATE INDEX IF NOT EXISTS "IX_GroupBuys_ExpiresAt" ON group_buys(expires_at);
CREATE INDEX IF NOT EXISTS "IX_GroupBuys_Status_ExpiresAt" ON group_buys(status, expires_at);
CREATE INDEX IF NOT EXISTS "IX_GroupBuyProducts_GroupBuyId" ON group_buy_products(group_buy_id);
CREATE INDEX IF NOT EXISTS "IX_GroupBuyProducts_Status" ON group_buy_products(status);
CREATE INDEX IF NOT EXISTS "IX_GroupBuyProducts_ProductId" ON group_buy_products(product_id);
CREATE UNIQUE INDEX IF NOT EXISTS "UX_GroupBuyProducts_GroupBuyId_ProductId"
    ON group_buy_products(group_buy_id, product_id);
CREATE INDEX IF NOT EXISTS "IX_GroupBuyParticipants_GroupBuyId" ON group_buy_participants(group_buy_id);
CREATE INDEX IF NOT EXISTS "IX_GroupBuyParticipants_ShopId" ON group_buy_participants(shop_id);
CREATE UNIQUE INDEX IF NOT EXISTS "UX_GroupBuyParticipants_GroupBuyId_ShopId"
    ON group_buy_participants(group_buy_id, shop_id);
CREATE INDEX IF NOT EXISTS "IX_GroupBuyParticipantItems_ParticipantId"
    ON group_buy_participant_items(participant_id);
CREATE INDEX IF NOT EXISTS "IX_GroupBuyParticipantItems_GroupBuyProductId"
    ON group_buy_participant_items(group_buy_product_id);
CREATE UNIQUE INDEX IF NOT EXISTS "UX_GroupBuyParticipantItems_ParticipantId_GroupBuyProductId"
    ON group_buy_participant_items(participant_id, group_buy_product_id);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_PlatformSettings_Key" ON platform_settings(key);
CREATE INDEX IF NOT EXISTS "IX_ShopOnboardingPayments_ShopId" ON shop_onboarding_payments(shop_id);
CREATE INDEX IF NOT EXISTS "IX_ShopOnboardingPayments_Status" ON shop_onboarding_payments(status);
CREATE UNIQUE INDEX IF NOT EXISTS "UX_ShopOnboardingPayments_PendingShop"
    ON shop_onboarding_payments(shop_id) WHERE status = 'pending';
CREATE UNIQUE INDEX IF NOT EXISTS "UX_ShopOnboardingPayments_PayFastPaymentId"
    ON shop_onboarding_payments(pay_fast_payment_id) WHERE pay_fast_payment_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS "IX_Notifications_SupplierId" ON notifications(supplier_id);
CREATE INDEX IF NOT EXISTS "IX_Notifications_SupplierId_IsRead" ON notifications(supplier_id, is_read);

-- Verify the authentication schema before marking this baseline as applied.
DO $$
DECLARE
    missing_table text;
BEGIN
    FOREACH missing_table IN ARRAY ARRAY[
        'roles', 'permissions', 'role_permissions', 'users', 'refresh_tokens',
        'auth_audit_logs', 'suppliers', 'spaza_shops'
    ]
    LOOP
        IF to_regclass('public.' || missing_table) IS NULL THEN
            RAISE EXCEPTION 'Required authentication table is missing: %', missing_table;
        END IF;
    END LOOP;
END $$;

-- Record the snake_case baseline applied by this script. The checked-in EF migration
-- predates the naming convention, so QA uses this idempotent SQL as its schema owner.
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260505033156_InitialCreate', '8.0.0')
ON CONFLICT DO NOTHING;

-- Seed the configurable once-off shop onboarding fee without overwriting admin changes.
INSERT INTO platform_settings (id, key, value, created_at, updated_at)
SELECT gen_random_uuid(), 'shop_onboarding_fee_amount', '150.00', NOW(), NOW()
WHERE NOT EXISTS (
    SELECT 1 FROM platform_settings WHERE key = 'shop_onboarding_fee_amount'
);

-- Seed required roles idempotently by role name.
INSERT INTO roles (id, name, description, is_active, created_at, updated_at)
SELECT gen_random_uuid(), seed.name, seed.description, true, NOW(), NOW()
FROM (VALUES
  ('supplier', 'Supplier role'),
  ('spaza_owner', 'Spaza shop owner role'),
  ('admin', 'Platform admin role'),
  ('customer', 'Consumer / customer role')
) AS seed(name, description)
WHERE NOT EXISTS (SELECT 1 FROM roles existing WHERE existing.name = seed.name);

-- Seed a default category idempotently by slug.
INSERT INTO categories (id, name, slug, sort_order, is_active, created_at, updated_at)
SELECT gen_random_uuid(), 'Groceries', 'groceries', 1, true, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE slug = 'groceries');

COMMIT;
